name: Auto Obfuscate edgetunnel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 3,12,16 * * *" 
  workflow_dispatch: 

env:
  REPO: "odaychina/edgetunnel"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v6

      - name: Check for Updates
        id: check_update
        run: |
          NEW_TS=$(date -d "$(curl -sI "https://api.github.com/repos/$REPO/commits?per_page=1" | grep -i '^date:' | awk '{print $2, $3, $4, $5}')" +%s)
          if [ -f "_worker.js" ] && (( $(date -u -r _worker.js +%s) >= NEW_TS )); then
            echo "UPDATE_NEEDED=false" >> $GITHUB_OUTPUT; exit 0
          fi
          echo "UPDATE_NEEDED=true" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        if: steps.check_update.outputs.UPDATE_NEEDED == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install obfuscator
        if: steps.check_update.outputs.UPDATE_NEEDED == 'true'
        run: npm install -g javascript-obfuscator

      - name: Obfuscate JS
        if: steps.check_update.outputs.UPDATE_NEEDED == 'true'
        run: |
          wget -O origin.js https://raw.githubusercontent.com/$REPO/main/_worker.js
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --string-array true \
          --string-array-encoding 'base64' \
          --string-array-threshold 0.75 \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --transform-object-keys true

      - name: Commit and Push
        if: steps.check_update.outputs.UPDATE_NEEDED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: '🤖 Auto obfuscate'
          file_pattern: '_worker.js' 
